name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest


    # Local DB Only
    # services:
    #   postgres:
    #     image: postgres:14
    #     env:
    #       POSTGRES_USER: mrkim
    #       POSTGRES_PASSWORD: 142536
    #       POSTGRES_DB: simple_bank
    #     ports:
    #       - 5400:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5


    steps:
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: Run migrations
      run: make migrateup

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Test
      run: make test
